name: PIPELINE API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --use-deprecated=legacy-resolver

      - name: Run tests
        run: python -m unittest discover -s testy -p '*_user.py'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v3
