name: PIPELINE API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --use-deprecated=legacy-resolver

    - name: Install OWASP ZAP
      run: |
        choco install owasp-zap

    - name: Run testy
      run: python -m unittest discover -s testy -p '*_user.py'

    - name: DAST Test
      run: |
        zap-baseline.py -t http://localhost:5000
