name: PIPELINE API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --use-deprecated=legacy-resolver

    - name: Run testy
      run: python -m unittest discover -s testy -p '*_user.py'

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Run Dependency-Check
      run: |
        mkdir dc-report
        curl -L -o dependency-check.zip https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.2-release.zip
        unzip dependency-check.zip -d dc
        dc/bin/dependency-check.bat --scan . --format ALL --out dc-report
