name: PIPELINE API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --use-deprecated=legacy-resolver

      - name: Run tests
        run: python -m unittest discover -s testy -p '*_user.py'

  analyze:
    name: CodeQL Analysis
    
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  dependency-review:
  
    name: Dependency review
    on:
      push:
        branches:
          - main
    permissions:
      contents: read

    jobs:
      dependency-review:
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: Dependency Review
            uses: actions/dependency-review-action@v4
            with:
              comment-summary-in-pr: always
              repo-token: ${{ secrets.GITHUB_TOKEN }}
              retry-on-snapshot-warnings: false
              retry-on-snapshot-warnings-timeout: 120
              warn-only: false
