name: PIPELINE API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --use-deprecated=legacy-resolver

      - name: Run tests
        run: python -m unittest discover -s testy -p '*_user.py'

      - name: Start API and wait for it to be ready
        run: |
          python app.py &
          sleep 10 

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:5000'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          allow_issue_writing: true
          issue_title: 'ZAP Baseline Scan Report'
          fail_action: true
          artifact_name: 'zap_scan'
          user: 'root'
